# Generated by Django 5.2.7 on 2025-10-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='drawing',
            name='height',
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name='drawing',
            name='width',
            field=models.IntegerField(default=640),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='strokes',
            field=models.JSONField(default=list),
        ),
    ]
